In [3]:
# import numpy as 
import numpy as np

In [4]:
list_1=[1,2,3]
np.array(list_1)


array([1, 2, 3])

In [5]:
list2=[[1,2,3,4],[3,2,1,4],[3,5,1,3]]
arr2=np.array(list2)
arr2


array([[1, 2, 3, 4],
       [3, 2, 1, 4],
       [3, 5, 1, 3]])

In [11]:
list3=[[[1,2,3],[4,5,6],[7,8,9]]]
arr3=np.array(list3)
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
###Attributes

In [14]:
#shape
arr2.shape


(3, 4)

In [19]:
arr3.shape
arr3.flatten()
arr3.ndim


3

In [7]:
arr2.ndim

2

In [ ]:
## Create numpy arrays with built-in methods


In [22]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
zeros=np.zeros((1,4))
zeros

array([[0., 0., 0., 0.]])

In [26]:
identity=np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
### Linscpace --
### In the example bellow
### It creates a numpy array of number from 1 to 100 and divides them so that 10 elements are in the object

In [29]:
by_linspace=np.linspace(1,100,10)
by_linspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:

by_linspace.reshape(2,5)

array([[  1.,  12.,  23.,  34.,  45.],
       [ 56.,  67.,  78.,  89., 100.]])